// website/src/components/Footer.tsx
import { IconBrandGithub, IconBrandLinkedin } from '@tabler/icons-react';
import { useStateContext } from '../data/state';

export function Footer() {
  const { contact } = useStateContext();
  
  return (
    <footer id="contact" className="bg-card border-t border-border py-12">
      <div className="container mx-auto px-6 text-center">
        <div className="flex justify-center gap-6 mb-6">
          <a
            href={contact.githubUrl.href}
            target="_blank"
            rel="noreferrer"
            className="text-muted-foreground hover:text-foreground transition-colors"
          >
            <IconBrandGithub className="w-6 h-6" />
          </a>
          <a
            href={contact.linkedinUrl.href}
            target="_blank"
            rel="noreferrer"
            className="text-muted-foreground hover:text-foreground transition-colors"
          >
            <IconBrandLinkedin className="w-6 h-6" />
          </a>
        </div>
        <p className="text-muted-foreground">
          © {new Date().getFullYear()} {contact.name}. Built with React and Tailwind CSS.
        </p>
      </div>
    </footer>
  );
}

// website/src/app/components/footer.component/footer.component.ts
import { Component } from '@angular/core';
import { LucideAngularModule, Github, Linkedin } from 'lucide-angular';

@Component({
  selector: 'app-footer',
  imports: [LucideAngularModule],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {
  readonly githubIcon = Github;
  readonly linkedinIcon = Linkedin;

}

<footer id="contact" class="bg-card border-t border-border py-12">
  <div class="container mx-auto px-6 text-center">
    <div class="flex justify-center gap-6 mb-6">
      <a
        href="https://github.com/janthoXO"
        target="_blank"
        class="text-muted-foreground hover:text-foreground transition-colors"
      >
        <lucide-icon [img]="githubIcon" class="w-6 h-6"></lucide-icon>
      </a>
      <a
        href="https://www.linkedin.com/in/dennisjandow/"
        target="_blank"
        class="text-muted-foreground hover:text-foreground transition-colors"
      >
        <lucide-icon [img]="linkedinIcon" class="w-6 h-6"></lucide-icon>
      </a>
    </div>
    <p class="text-muted-foreground">
      © 2025 Dennis Jandow. Built with Angular and Tailwind CSS.
    </p>
  </div>
</footer>
