// website/src/app/components/projects.component/projects.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { State } from '../../data/state';
import { GithubService } from '../../service/github.service';
import { HlmCardImports } from '../../../../libs/ui/ui-card-helm/src';
import { HlmButton } from '../../../../libs/ui/ui-button-helm/src';
import { LucideAngularModule, ExternalLink, Github } from 'lucide-angular';

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [CommonModule, ...HlmCardImports, HlmButton, LucideAngularModule],
  templateUrl: './projects.component.html',
  styleUrl: './projects.component.css',
})
export class ProjectsComponent implements OnInit {
  // Icons
  readonly externalLinkIcon = ExternalLink;
  readonly githubIcon = Github;
  
  state = inject(State);
  githubService = inject(GithubService);

  get projects() {
    return this.state.projectEntries();
  }

  ngOnInit() {
    this.githubService.loadGithubProjects();
  }

  formatDate(date: Date | string | null): string {
    if (date === null) return 'Present';
    if (date === 'PRESENT') return 'Present';
    if (date instanceof Date) {
      return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
      });
    }
    return String(date);
  }
}

<section id="projects" class="py-20 bg-secondary/5">
  <div class="container mx-auto px-6">
    <div class="text-center mb-16">
      <h2 class="text-4xl md:text-5xl font-bold text-foreground mb-4">
        Featured Projects
      </h2>
      <p class="text-xl text-muted-foreground max-w-2xl mx-auto">
        A showcase of my recent work and contributions to the developer
        community
      </p>
    </div>

    <div
      class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-7xl mx-auto"
    >
      @for (project of projects; track project.id) {
      <div
        hlmCard
        class="group shadow-lg hover:shadow-2xl transition-all duration-500 hover:-translate-y-2 overflow-hidden"
      >
        <!-- Project Header -->
        <div hlmCardHeader>
          <div class="flex items-start justify-between mb-4">
            <h3
              hlmCardTitle
              class="text-xl font-bold text-foreground group-hover:text-primary transition-colors"
            >
              {{ project.name }}
            </h3>
            @if (project.link) {
            <a
              [href]="project.link.href"
              target="_blank"
              class="text-muted-foreground hover:text-primary transition-colors"
            >
              <lucide-icon
                [img]="externalLinkIcon"
                class="w-5 h-5"
              ></lucide-icon>
            </a>
            }
          </div>

          <!-- Project Short Description -->
          <p
            hlmCardDescription
            class="text-muted-foreground text-sm mb-4 line-clamp-3"
          >
            {{ project.shortDescription }}
          </p>

          <!-- Date Range -->
          <div class="text-xs text-muted-foreground mb-4">
            {{ formatDate(project.startDate) }} -
            {{ formatDate(project.endDate) }}
          </div>
        </div>

        <!-- Project Description (HTML Content) -->
        @if (project.description) {
        <div hlmCardContent class="border-t border-border pt-4">
          <div
            class="project-description-content"
            [innerHTML]="project.description"
          ></div>
        </div>
        }

        <!-- Project Actions -->
        <div hlmCardFooter>
          <div class="w-full">
            @if (project.link) {
            <button hlmBtn class="w-full text-center text-sm font-medium p-0">
              <a class="w-full" href="{{ project.link.href }}" target="_blank">
                View Project
              </a>
            </button>
            }
          </div>
        </div>

        <!-- Hover Effect Overlay -->
        <div
          class="absolute inset-0 bg-gradient-to-t from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none"
        ></div>
      </div>
      }
    </div>

    <!-- Add Project CTA -->
    <div class="text-center mt-16">
      <div hlmCard class="mx-auto max-w-2xl">
        <div hlmCardHeader>
          <h3 hlmCardTitle class="flex items-center justify-center gap-4">
            <span class="text-4xl">🚀</span>
            <span class="text-2xl font-bold text-foreground"
              >Want to see more?</span
            >
            <span class="text-4xl">🚀</span>
          </h3>
        </div>
        <div hlmCardContent>
          <p class="text-muted-foreground">
            Check out all my projects and contributions on GitHub
          </p>
        </div>
        <div hlmCardFooter>
          <button hlmBtn class="w-full p-0">
            <a
              href="https://github.com/janthoXO"
              target="_blank"
              class="w-full inline-flex justify-center gap-2 text-sm font-medium"
            >
              <lucide-icon [img]="githubIcon" class="w-4 h-4"></lucide-icon>
              Visit GitHub Profile
            </a>
          </button>
        </div>
      </div>
    </div>
  </div>
</section>

// src/components/projects.tsx
import { useEffect, useState } from "react"
import { ExternalLinkIcon, StarIcon } from "lucide-react"

import { GithubIcon } from "@/components/brand-icons"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { SectionHeading } from "@/components/section-heading"
import { basics, projects, type Project } from "@/data"
import { timeAgo } from "@/lib/format"

type Repo = {
  name: string
  description: string | null
  language: string | null
  stargazers_count: number
  updated_at: string
  topics: string[]
}

function useRepo(link: string) {
  const [repo, setRepo] = useState<Repo>()
  useEffect(() => {
    const repoPath = link.match(/^https:\/\/github\.com\/([^/]+\/[^/]+)/)?.[1]
    if (!repoPath) return
    const ctrl = new AbortController()
    fetch(`https://api.github.com/repos/${repoPath}`, { signal: ctrl.signal })
      .then((r) => (r.ok ? r.json() : Promise.reject(r.statusText)))
      .then(setRepo)
      .catch((e) => ctrl.signal.aborted || console.error(e))
    return () => ctrl.abort()
  }, [link])
  return repo
}

function ProjectCard({ project }: { project: Project }) {
  const repo = useRepo(project.link)
  const tags = repo?.topics.length ? repo.topics : []

  return (
    <Card className="reveal transition-transform duration-300 hover:-translate-y-1">
      <CardHeader>
        <CardTitle className="text-lg font-semibold">
          {repo?.name ?? project.name}
        </CardTitle>
        <CardAction>
          <Button
            variant="ghost"
            size="icon-sm"
            aria-label={`Open ${project.name}`}
            nativeButton={false}
            render={<a href={project.link} target="_blank" rel="noreferrer" />}
          >
            <ExternalLinkIcon />
          </Button>
        </CardAction>
      </CardHeader>
      <CardContent className="flex flex-1 flex-col gap-4">
        <p className="text-muted-foreground">
          {repo?.description || project.description}
        </p>
        <div className="flex items-center gap-3 text-xs text-muted-foreground">
          <Badge variant="outline">{repo?.language ?? project.language}</Badge>
          {repo && (
            <>
              <span className="flex items-center gap-1">
                <StarIcon className="size-3" /> {repo.stargazers_count}
              </span>
              <span className="ml-auto">
                Updated {timeAgo(repo.updated_at)}
              </span>
            </>
          )}
        </div>
        {tags.length > 0 && (
          <div className="flex flex-wrap gap-1.5">
            {tags.slice(0, 6).map((tag) => (
              <Badge key={tag} variant="secondary">
                {tag}
              </Badge>
            ))}
          </div>
        )}
      </CardContent>
      <CardFooter>
        <Button
          className="w-full"
          nativeButton={false}
          render={<a href={project.link} target="_blank" rel="noreferrer" />}
        >
          View Project
        </Button>
      </CardFooter>
    </Card>
  )
}

export function Projects() {
  return (
    <section id="projects" className="flex flex-col gap-12">
      <SectionHeading
        title="Featured Projects"
        subtitle="A showcase of my recent work and contributions"
      />
      <div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,20rem),24rem))] justify-center gap-6">
        {projects.map((p) => (
          <ProjectCard key={p.link} project={p} />
        ))}
      </div>
      <Card className="reveal mx-auto w-full max-w-xl text-center">
        <CardHeader>
          <CardTitle className="text-2xl font-semibold">
            Want to see more?
          </CardTitle>
          <CardDescription>
            Check out all my projects and contributions on GitHub
          </CardDescription>
        </CardHeader>
        <CardFooter className="justify-center">
          <Button
            size="lg"
            nativeButton={false}
            render={<a href={basics.github} target="_blank" rel="noreferrer" />}
          >
            <GithubIcon data-icon="inline-start" />
            Visit GitHub Profile
          </Button>
        </CardFooter>
      </Card>
    </section>
  )
}
