// website/src/components/Projects.tsx
import { useStateContext } from '../data/state';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from './ui/card';
import { Button } from './ui/button';
import { ExternalLink } from 'lucide-react';
import { IconBrandGithub } from '@tabler/icons-react';
import { useEffect } from 'react';
import type { ProjectEntry } from '../domain/project.model';
import { fetchRepoData, transformGithubDataToProjectEntry } from '../service/github';

function formatDate(date: Date | null): string {
  if (date === null) return 'Present';
  if (date instanceof Date) {
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
    });
  }
  return String(date);
}

export function Projects() {
  const { projectEntries, setProject } = useStateContext();

  useEffect(() => {
    projectEntries.forEach(async (project) => {
      if (!project.link || project.link.hostname !== 'github.com') {
        return;
      }

      const match = project.link.href.match(/github\.com\/([^/]+)\/([^/]+)/);
      if (!match) return;

      const [, owner, repo] = match;
      try {
        const repoData = await fetchRepoData(owner, repo);
        const newProject = transformGithubDataToProjectEntry(repoData, project);
        setProject(newProject);
      } catch (err) {
        console.error('Error fetching github project data:', err);
      }
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div id="projects" className="container mx-auto py-20">
      <div className="text-center mb-16">
        <h2 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
          Featured Projects
        </h2>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          A showcase of my recent work and contributions to the developer community
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-7xl mx-auto">
        {projectEntries.map((project: ProjectEntry) => (
          <Card
            key={project.id}
            className="hover:shadow-2xl transition-all duration-500 hover:-translate-y-2 overflow-hidden flex flex-col h-full"
          >
            <CardHeader className="flex-1">
              <div className="flex items-start justify-between mb-4 gap-4">
                <CardTitle className="text-xl font-bold text-foreground">
                  {project.name}
                </CardTitle>
                {project.link && (
                  <a
                    href={project.link.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-muted-foreground hover:text-primary transition-colors flex-shrink-0"
                  >
                    <ExternalLink className="w-5 h-5" />
                  </a>
                )}
              </div>

              <CardDescription className="text-muted-foreground text-sm mb-4 line-clamp-3">
                {project.shortDescription}
              </CardDescription>

              <div className="text-xs text-muted-foreground mb-4">
                {formatDate(project.startDate)} - {formatDate(project.endDate)}
              </div>
            </CardHeader>

            {project.description && (
              <CardContent className="border-t border-border pt-4">
                <div
                  className="project-description-content"
                  dangerouslySetInnerHTML={{ __html: project.description }}
                />
              </CardContent>
            )}

            <CardFooter className="mt-auto">
              <div className="w-full">
                {project.link && (
                  <Button className="w-full" asChild>
                    <a href={project.link.href} target="_blank" rel="noopener noreferrer">
                      View Project
                    </a>
                  </Button>
                )}
              </div>
            </CardFooter>
          </Card>
        ))}
      </div>

      {/* Add Project CTA */}
      <div className="text-center mt-16">
        <Card className="mx-auto max-w-2xl">
          <CardHeader>
            <CardTitle className="flex items-center justify-center gap-4">
              <span className="text-4xl">🚀</span>
              <span className="text-2xl font-bold text-foreground">Want to see more?</span>
              <span className="text-4xl">🚀</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Check out all my projects and contributions on GitHub
            </p>
          </CardContent>
          <CardFooter>
            <Button className="w-full" asChild>
              <a
                href="https://github.com/janthoXO"
                target="_blank"
                rel="noopener noreferrer"
                className="w-full inline-flex justify-center items-center gap-2"
              >
                <IconBrandGithub className="w-4 h-4" />
                Visit GitHub Profile
              </a>
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}

// website/src/app/components/projects.component/projects.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { State } from '../../data/state';
import { GithubService } from '../../service/github.service';
import { HlmCardImports } from '../../../../libs/ui/ui-card-helm/src';
import { HlmButton } from '../../../../libs/ui/ui-button-helm/src';
import { LucideAngularModule, ExternalLink, Github } from 'lucide-angular';

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [CommonModule, ...HlmCardImports, HlmButton, LucideAngularModule],
  templateUrl: './projects.component.html',
  styleUrl: './projects.component.css',
})
export class ProjectsComponent implements OnInit {
  // Icons
  readonly externalLinkIcon = ExternalLink;
  readonly githubIcon = Github;
  
  state = inject(State);
  githubService = inject(GithubService);

  get projects() {
    return this.state.projectEntries();
  }

  ngOnInit() {
    this.githubService.loadGithubProjects();
  }

  formatDate(date: Date | string | null): string {
    if (date === null) return 'Present';
    if (date === 'PRESENT') return 'Present';
    if (date instanceof Date) {
      return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
      });
    }
    return String(date);
  }
}

<section id="projects" class="py-20 bg-secondary/5">
  <div class="container mx-auto px-6">
    <div class="text-center mb-16">
      <h2 class="text-4xl md:text-5xl font-bold text-foreground mb-4">
        Featured Projects
      </h2>
      <p class="text-xl text-muted-foreground max-w-2xl mx-auto">
        A showcase of my recent work and contributions to the developer
        community
      </p>
    </div>

    <div
      class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-7xl mx-auto"
    >
      @for (project of projects; track project.id) {
      <div
        hlmCard
        class="group shadow-lg hover:shadow-2xl transition-all duration-500 hover:-translate-y-2 overflow-hidden"
      >
        <!-- Project Header -->
        <div hlmCardHeader>
          <div class="flex items-start justify-between mb-4">
            <h3
              hlmCardTitle
              class="text-xl font-bold text-foreground group-hover:text-primary transition-colors"
            >
              {{ project.name }}
            </h3>
            @if (project.link) {
            <a
              [href]="project.link.href"
              target="_blank"
              class="text-muted-foreground hover:text-primary transition-colors"
            >
              <lucide-icon
                [img]="externalLinkIcon"
                class="w-5 h-5"
              ></lucide-icon>
            </a>
            }
          </div>

          <!-- Project Short Description -->
          <p
            hlmCardDescription
            class="text-muted-foreground text-sm mb-4 line-clamp-3"
          >
            {{ project.shortDescription }}
          </p>

          <!-- Date Range -->
          <div class="text-xs text-muted-foreground mb-4">
            {{ formatDate(project.startDate) }} -
            {{ formatDate(project.endDate) }}
          </div>
        </div>

        <!-- Project Description (HTML Content) -->
        @if (project.description) {
        <div hlmCardContent class="border-t border-border pt-4">
          <div
            class="project-description-content"
            [innerHTML]="project.description"
          ></div>
        </div>
        }

        <!-- Project Actions -->
        <div hlmCardFooter>
          <div class="w-full">
            @if (project.link) {
            <button hlmBtn class="w-full text-center text-sm font-medium p-0">
              <a class="w-full" href="{{ project.link.href }}" target="_blank">
                View Project
              </a>
            </button>
            }
          </div>
        </div>

        <!-- Hover Effect Overlay -->
        <div
          class="absolute inset-0 bg-gradient-to-t from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none"
        ></div>
      </div>
      }
    </div>

    <!-- Add Project CTA -->
    <div class="text-center mt-16">
      <div hlmCard class="mx-auto max-w-2xl">
        <div hlmCardHeader>
          <h3 hlmCardTitle class="flex items-center justify-center gap-4">
            <span class="text-4xl">🚀</span>
            <span class="text-2xl font-bold text-foreground"
              >Want to see more?</span
            >
            <span class="text-4xl">🚀</span>
          </h3>
        </div>
        <div hlmCardContent>
          <p class="text-muted-foreground">
            Check out all my projects and contributions on GitHub
          </p>
        </div>
        <div hlmCardFooter>
          <button hlmBtn class="w-full p-0">
            <a
              href="https://github.com/janthoXO"
              target="_blank"
              class="w-full inline-flex justify-center gap-2 text-sm font-medium"
            >
              <lucide-icon [img]="githubIcon" class="w-4 h-4"></lucide-icon>
              Visit GitHub Profile
            </a>
          </button>
        </div>
      </div>
    </div>
  </div>
</section>
